server = input("What's YOUR fucking name? ")
mark = input("What's this stupid fuck's name? ")
item = input("What did he fucking order? ")
quant = input("How many did he fucking order? ")
price = input("How much do they fucking cost? ")
disc = input("What % discount? (example: 17% = 0.17) ")
charge = int(quant) * int(price)
bill = ((charge)-((charge)*float(disc)))
final = (float(bill)*(1.17))
print("{},\n charge that stupid fucker {}\n ${} \nfor those {} {}.".format(server, mark, final, quant, item))
